CREATE TABLE if not exists tg_data (
                         User_key INTEGER generated by default as identity primary key,
                         id INTEGER,
                         name text NOT NULL,
                         msg_numb INTEGER NOT NULL,
                         score INTEGER,
                         chat_Id INTEGER
);

CREATE TABLE IF NOT EXISTS chats (
                         chat_Id INTEGER PRIMARY KEY
);